#!/bin/bash
setterm -foreground green
echo "¿conect to SSH? --hp --bangho --blackarch --termux"
setterm -foreground white
while [ -n "$1" ]; do 

        case "$1" in

    --hp)
ssh lucas@192.168.0.240 -p 1234
	;;
--blackarch)
ssh user@192.168.0.237 -p 22
	;;
   --bangho)
ssh lucas@192.168.0.130 -p 22
	;;
   --termux)
ssh u0_a164@192.168.0.102 -p 22
	;;
  *)
	echo "Option $1 not recognized" ;; 

        esac

        shift

done

